apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31366
  selector:
    app: my-app
  type: NodePort
