apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-replicaset
    labels:
      name: myaapset
      app: front-end
spec: 
    template:
      metadata:
         name: my
         labels:
           app: front-end
           name: appmy
      spec:
         containers:
           - image: nginx
             name: my-nginx
    replicas: 2
    selector:
         matchLabels:
            app: front-end 

